[project]
name = "movielens-venv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.1",
    "notebook>=7.4.5",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
]
